### PR TITLE
Added support for pam_duo

### PR DESCRIPTION
**Pull request by Kahn**

### CODE REVIEW

**Comment by samcday** [comment]
@CoffeeAndCode any plans to merge this? :)

**Comment by Kahn** [comment]
@jonknapp ping

**Comment by jonknapp** [comment]
I am really sorry about missing this @Kahn. I changed my username to free up my old one for the company and must have missed a notification in the process.

I'm not sure if this works or not, but I'm guessing you did your due diligence. Plus it can always be changed if something breaks.  Thanks for the pull request!

**Comment by jonknapp** [comment]
Added new tag `v1.1.0` and updated [Galaxy](https://galaxy.ansible.com/detail#/role/396).

**Pull request merged**
